### PR TITLE
ENH: Guess open linear transform formats

### PR DESCRIPTION
**Pull request by oesteban**
EAFP implementation of loading linear transforms without specifying the format of the file.

Resolves: #86.
Resolves: #87.
Resolves: #107.

### CODE REVIEW

**Comment by oesteban** [comment]
@effigies do you want to bump this?

Also a good warming up for @mgxd, now he's returning :)

**Comment by effigies** [comment]
Sorry, yes, I'll try to get back to this this week.

**Comment by oesteban** [comment]
Bumping up

**Comment by oesteban** [comment]
Any chance to get more eyes on this? @mgxd @effigies

**Pull request merged**
